WITH CTE AS (
	SELECT
		DT_REFE
		, 1 AS QTD
		, CASE
			WHEN CATEGORIA = 'Negocio' THEN 1
			ELSE 0
		END AS IND_CORR_NEG
		, CASE
			WHEN CATEGORIA = 'Pessoal' THEN 1
			ELSE 0
		END AS IND_CORR_PESS
		, CAST(DISTANCIA AS INT) AS DISTANCIA
		, CASE
			WHEN PROPOSITO LIKE '%Reuni%' THEN 1
			ELSE 0
		END AS IND_CORR_REUNI
		, CASE
			WHEN PROPOSITO NOT LIKE '%Reuni%' THEN 1
			ELSE 0
		END AS IND_CORR_NAO_REUNI
	FROM info_transportes
)
SELECT
	DT_REFE
	, SUM(QTD)					AS QT_CORR
	, SUM(IND_CORR_NEG)			AS QT_CORR_NEG
	, SUM(IND_CORR_PESS)		AS QT_CORR_PESS
	, MAX(DISTANCIA)			AS VL_MAX_DIST
	, MIN(DISTANCIA)			AS VL_MIN_DIST
	, AVG(DISTANCIA)			AS VL_AVG_DIST
	, SUM(IND_CORR_REUNI)		AS QT_CORR_REUNI
	, SUM(IND_CORR_NAO_REUNI)	AS QT_CORR_NAO_REUNI
FROM CTE
GROUP BY DT_REFE
